version: '3.7'

services:
    gitlab:
        image: 'gitlab/gitlab-ce:latest'
        restart: always
        hostname: 'gitlab.example.com'
        environment:
            GITLAB_OMNIBUS_CONFIG: |
                external_url 'http://gitlab.example.com'
        ports:
            - '8081:80'
        volumes:
            - './gitlab/config:/etc/gitlab'
            - './gitlab/logs:/var/log/gitlab'
            - './gitlab/data:/var/opt/gitlab'

    bitbucket:
        image: 'atlassian/bitbucket-server:latest'
        restart: always
        volumes:
            - './bitbucket:/var/atlassian/application-data/bitbucket'
        ports:
            - '7990:7990'
            - '7999:7999'

    jira:
        image: 'cptactionhank/atlassian-jira:latest'
        restart: always
        volumes:
            - './jira:/var/atlassian/jira'
        ports:
            - '8080:8080'

    zookeeper:
        image: 'bitnami/zookeeper:latest'
        environment:
            - ALLOW_ANONYMOUS_LOGIN=yes
        ports:
            - '2181:2181'

    kafka:
        image: 'bitnami/kafka:latest'
        environment:
            - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
            - ALLOW_PLAINTEXT_LISTENER=yes
            - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093,EXTERNAL://:9094
            - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092,EXTERNAL://localhost:9094
            - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,EXTERNAL:PLAINTEXT,PLAINTEXT:PLAINTEXT
        ports:
            - '9092:9092'
            - '9093:9093'
            - '9094:9094'
        depends_on:
            - zookeeper

    kafka-ui:
        image: 'provectuslabs/kafka-ui:latest'
        ports:
            - '8080:8080'
        environment:
            - KAFKA_CLUSTERS_0_NAME="🔥☺️🔥"
            - KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS=kafka:9092
        depends_on:
            - kafka
