version: '3.7'

services:
    zookeeper:
        image: 'bitnami/zookeeper:latest'
        environment:
            - ALLOW_ANONYMOUS_LOGIN=yes
        ports:
            - '2181:2181'

    kafka:
        image: 'bitnami/kafka:latest'
        environment:
            - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
            - ALLOW_PLAINTEXT_LISTENER=yes
            - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093,EXTERNAL://:9094
            - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092,EXTERNAL://localhost:9094
            - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,EXTERNAL:PLAINTEXT,PLAINTEXT:PLAINTEXT
        ports:
            - '9092:9092'
            - '9093:9093'
            - '9094:9094'
        depends_on:
            - zookeeper

    kafka-ui:
        image: 'provectuslabs/kafka-ui:latest'
        ports:
            - '8080:8080'
        environment:
            - KAFKA_CLUSTERS_0_NAME="🔥☺️🔥"
            - KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS=kafka:9092
        depends_on:
            - kafka

    postgres:
        image: postgres:latest
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
            POSTGRES_DB: geniusrise
        ports:
            - '5432:5432'

    redis:
        image: redis:latest
        ports:
            - '6379:6379'

    dynamodb:
        image: amazon/dynamodb-local:latest
        ports:
            - '8000:8000'
